# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'converot_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(361, 193)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 341, 131))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.progressBar_vw = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar_vw.setGeometry(QtCore.QRect(10, 50, 211, 31))
        self.progressBar_vw.setProperty("value", 0)
        self.progressBar_vw.setObjectName("progressBar_vw")
        self.Open_file_vw = QtWidgets.QPushButton(self.groupBox)
        self.Open_file_vw.setGeometry(QtCore.QRect(10, 20, 91, 23))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.Open_file_vw.setFont(font)
        self.Open_file_vw.setObjectName("Open_file_vw")
        self.name_file_vw = QtWidgets.QLabel(self.groupBox)
        self.name_file_vw.setGeometry(QtCore.QRect(130, 20, 171, 16))
        self.name_file_vw.setText("")
        self.name_file_vw.setObjectName("name_file_vw")
        self.RUN_vw = QtWidgets.QPushButton(self.groupBox)
        self.RUN_vw.setGeometry(QtCore.QRect(224, 50, 101, 23))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.RUN_vw.setFont(font)
        self.RUN_vw.setObjectName("RUN_vw")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 361, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Open_file_vw.setText(_translate("MainWindow", "Оберіть файл"))
        self.RUN_vw.setText(_translate("MainWindow", "Почати обробку"))
